export const MEDIA = {
  // Switch codepush

  IMAGE_LOGO: require("../assets/images/logo-app.png"),
  IMAGE_BACKGROUND_LOGIN: require("../assets/images/backgroundLogin.png"),
  IMAGE_LOAD_REGISTER: require("../assets/images/loadRegister.png"),
  ICON_TICK: require("../assets/images/Splash.png"),
  IMAGE_SPLASH: require("../assets/images/Splash.png"),
  IMAGE_BG_INFO: require("../assets/images/bg_img_info.png"),
  IMAGE_BG_IMPORTPD: require("../assets/images/bg_importProduct.png"),
  PRODUCT_DETAIL: require("../assets/images/product-detail.png"),
  PAYMENT_SUCCESS: require("../assets/images/payment-success-img.png"),
  PAYMENT_SUCCESS_SUPPLIER: require("../assets/images/payment-success-npp.png"),
  IMAGE_BC: require("../assets/images/bankcard1.png"),
  LOGO_BOARDING_1: require("../assets/images/on_broad_1.png"),
  LOGO_BOARDING_2: require("../assets/images/on_broad_2.png"),
  LOGO_BOARDING_3: require("../assets/images/on_broad_3.png"),
  IMAGE_WAITING: require("../assets/images/waiting.png"),
  IMAGE_WAITING_2: require("../assets/images/pheduyet.png"),
  IMAGE_SUCCESS: require("../assets/images/success.png"),
  IMAGE_REJECT: require("../assets/images/reject.png"),
  IMAGE_HUAWAI: require("../assets/images/huawei.png"),
  IMAGE_AVT: require("../assets/images/avatar.png"),
  IMAGE_SUCCESS_TOPUP: require("../assets/images/img_success_topup.png"),
};
